export const add = 'https://oss.suning.com/sffe/sffe/add.png'
export const arrowRight = 'https://oss.suning.com/sffe/sffe/arrowRight202104201601.png'
export const bottomBg = 'https://oss.suning.com/sffe/sffe/bottomBg.png'
export const backBlack = 'https://oss.suning.com/sffe/sffe/backBlack.png'
export const backWhite = 'https://oss.suning.com/sffe/sffe/backWhite.png'
export const goods = 'https://oss.suning.com/sffe/sffe/goods.png'
export const fire = 'https://oss.suning.com/sffe/sffe/fire.png'
export const one = 'https://oss.suning.com/sffe/sffe/oneIcon.png'
export const order = 'https://oss.suning.com/sffe/sffe/order.png'
export const shopCart = 'https://oss.suning.com/sffe/sffe/shopCart.png'
export const discount = 'https://oss.suning.com/sffe/sffe/discount.png'
export const second = 'https://oss.suning.com/sffe/sffe/twoIcon.png'
export const third = 'https://oss.suning.com/sffe/sffe/threeIcon.png'
export const left = 'https://oss.suning.com/sffe/sffe/left.png'

export const subtract_disabled = 'https://oss.suning.com/sffe/sffe/stepper_subtract_disabled.png'
export const subtract_active = 'https://oss.suning.com/sffe/sffe/stepper_subtract_active.png'
export const single_add = 'https://oss.suning.com/sffe/sffe/single_add.png'
export const add_disabled = 'https://oss.suning.com/sffe/sffe/stepper_add_disabled.png'
export const add_active = 'https://oss.suning.com/sffe/sffe/stepper_add_active.png'

export const default_goods_img = 'https://oss.suning.com/sffe/sffe/default_goods.png'

export const banner = 'https://oss.suning.com/sffe/sffe/banner20210610.png'
export const titleBg = 'https://oss.suning.com/sffe/sffe/title20210610.png'

export const cart = 'https://oss.suning.com/srcfews/lsypc/cpgoods/cart.png'
export const cart_n = 'https://oss.suning.com/srcfews/lsypc/cpgoods/cart_n.png'
export const cart_t = 'https://oss.suning.com/srcfews/lsypc/cpgoods/cart_t.png'
export const close = 'https://oss.suning.com/srcfews/lsypc/cpgoods/close.png'
export const coupon_bg = 'https://oss.suning.com/srcfews/lsypc/cpgoods/coupon_bg.png'
export const head_bg = 'https://oss.suning.com/srcfews/lsypc/cpgoods/head_bg.png'
export const search = 'https://oss.suning.com/srcfews/lsypc/cpgoods/search.png'
export const right_blue = 'https://oss.suning.com/srcfews/lsypc/cpgoods/right_blue.png'
export const gotop = 'https://oss.suning.com/srcfews/lsypc/cpgoods/gotop.png'

export const store = 'https://oss.suning.com/sffe/sffe/member-analysis-store.png'
export const card_bg = 'https://oss.suning.com/sffe/sffe/member-analysis-card_bg.png'
export const member_analysis_broken = 'https://oss.suning.com/sffe/sffe/member-analysis-broken.png'
export const member_analysis_chart = 'https://oss.suning.com/sffe/sffe/member-analysis-chart.png'
export const member_analysis_crown = 'https://oss.suning.com/sffe/sffe/member-analysis-crown.png'
export const member_analysis_money = 'https://oss.suning.com/sffe/sffe/member-analysis-money.png'
export const member_analysis_filter = 'https://oss.suning.com/sffe/sffe/member-analysis-filter.png'
export const default_head = 'https://oss.suning.com/sffe/sffe/default_head.png'
export const phone_green = 'https://oss.suning.com/sffe/sffe/phone_green.png'
export const member_analysis_idea = 'https://oss.suning.com/sffe/sffe/member-analysis-idea.png'
export const member_analysis_interrogation = 'https://oss.suning.com/sffe/sffe/member_analysis_interrogation.png'
export const member_analysis_buy = 'https://oss.suning.com/sffe/sffe/member_analysis_buy.png'
export const checkbox_checked = 'https://oss.suning.com/sffe/sffe/checkbox_checked.png'
export const checkbox_uncheck = 'https://oss.suning.com/sffe/sffe/checkbox_uncheck.png'
export const purchase_icon = 'https://oss.suning.com/srcfews/lsypc/cpgoods/puchaseIcon.png'
export const coupon_item_bg = 'https://oss.suning.com/srcfews/lsypc/cpgoods/coupon_item_bg2.png'
export const member_analysis_bg = 'https://oss.suning.com/sffe/sffe/member_analysis_bg.png'
export const member_analysis_fop = 'https://oss.suning.com/sffe/sffe/member_analysis_fop2.png'
export const lion_search = 'https://oss.suning.com/sffe/sffe/lion_serach20220212.png'
export const no_coupon = 'https://oss.suning.com/srcfews/lsypc/cpgoods/no_coupon.png'

export const lsy_no_data = 'https://oss.suning.com/sffe/sffe/lsy_no_data.png'
export const menu_close = 'https://oss.suning.com/sffe/sffe/menu-close.png'
export const menu_expland = 'https://oss.suning.com/sffe/sffe/menu-expland.png'
export const goods_classific = 'https://oss.suning.com/sffe/sffe/fenlei.png'

export const ic_garbage = 'https://oss.suning.com/sffe/sffe/ic_garbage.png'
export const ic_close = 'https://oss.suning.com/sffe/sffe/ic_close.png'
export const ic_search_grey = 'https://oss.suning.com/sffe/sffe/ic_search_grey.png'
export const ic_arrow_normal = 'https://oss.suning.com/sffe/sffe/ic_arrow_normal.png'
export const ic_arrow_up = 'https://oss.suning.com/sffe/sffe/ic_arrow_up.png'
export const ic_arrow_down = 'https://oss.suning.com/sffe/sffe/ic_arrow_down.png'
export const ic_grey_arrow_down = 'https://oss.suning.com/sffe/sffe/ic_grey_arrow_down.png'
export const ic_grey_arrow_up = 'https://oss.suning.com/sffe/sffe/ic_grey_arrow_up.png'
export const tab_model_close = 'https://oss.suning.com/sffe/sffe/tab-model-close.png'
export const question_mark = 'https://oss.suning.com/sffe/sffe/question_mark.png'
export const config_modal_close = 'http://oss.suning.com/sffe/sffe/config_modal_close.png'
